#!/bin/sh

# Répertoire de travail
SH_BASE="${SH_BASE:-`pwd`}"

#Scripts de live-helper
. "${LH_BASE:-/usr/share/live-helper}"/functions.sh

lh_clean noautoconfig --all ${@}

rm -f build.log
rm -rf cache .stage
rm -f config/binary config/bootstrap config/chroot config/common config/source
rm -f ${SH_BASE}/config/chroot_local-includes/usr/share/doc/satan-manual/html/img/*.png	
rm -f ${SH_BASE}/config/chroot_local-includes/usr/share/doc/satan-manual/html/*.png	
rm -rf ${SH_BASE}/config/chroot_local-includes/usr/share/framework-3.1 ${SH_BASE}/config/chroot_local-includes/usr/share/hydra-5.4-src ${SH_BASE}/config/chroot_local-includes/usr/share/libssh-0.2 ${SH_BASE}/config/chroot_local-includes/usr/share/netkit
rm -f ${SH_BASE}/config/chroot_local-includes/usr/share/hydra-libssh0.2.patch
rm -rf ${SH_BASE}/config/chroot_local-includes/var/www
rm -f ${SH_BASE}/config/chroot_local-includes/usr/share/ios/*
rm -f ${SH_BASE}/config/chroot_local-includes/usr/share/itrafgenubuntu.deb
rm -rf ${SH_BASE}/config/chroot_local-packages/
rm -rf ${SH_BASE}/doc/satan-manual/config/
rm -rf ${SH_BASE}/doc/satan-manual/scripts/

# Remove empty directories in config tree
if ls config/*/ > /dev/null 2>&1
then
	rmdir --ignore-fail-on-non-empty config/*/
fi

if [ -d config ]
then
	rmdir --ignore-fail-on-non-empty config
fi
